export { smartClone } from './clone.js'
export type { CloneOptions, CloneResult } from './clone.js'
export { discoverFiles } from './file-discovery.js'
export type { RepoFile } from './file-discovery.js'
export { selectAnalyzableFiles } from './select-analyzable.js'
export type { SelectedFile, FileCategory } from './select-analyzable.js'
export { detectWorkspaces } from './detect-workspaces.js'
export type { ServiceUnit } from './detect-workspaces.js'
export { checkRepoSize } from './repo-size-guard.js'
export { extractRoutes } from './framework-extractors/index.js'
export type { ExtractedRoute } from './framework-extractors/index.js'
